schema_version = 1

[protocol]
abi_version = 1
protocol_version = 8

[toolchain]
byond = "516.1687"

[capabilities]
features = [
	"aphelion_reactions",
	"katmos",
	"katmos_slow_decompression",
	"superconductivity",
	"turf_processing",
]
