//THIS FILE IS AUTOMATICALLY GENERATED BY DOGMOS, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

#define DOGMOS (world.system_type == UNIX ? "libdogmos" : "dogmos")

/proc/dogmos_abi_version()
	return call_ext(DOGMOS, "byond:dogmos_abi_version_ffi")()

/proc/dogmos_callback_drain(max_events)
	return call_ext(DOGMOS, "byond:dogmos_callback_drain_ffi")(max_events)

/proc/dogmos_continuation_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_adjust_multiple_ffi")(fields)

/proc/dogmos_continuation_cancel(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_cancel_ffi")(fields)

/proc/dogmos_continuation_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_command_ffi")(fields)

/proc/dogmos_continuation_resume(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_resume_ffi")(fields)

/proc/dogmos_feature_fingerprint()
	return call_ext(DOGMOS, "byond:dogmos_feature_fingerprint_ffi")()

/proc/dogmos_gas_metadata_install(numeric_records, keys, names, product_records)
	return call_ext(DOGMOS, "byond:dogmos_gas_metadata_install_ffi")(numeric_records, keys, names, product_records)

/proc/dogmos_mixture_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_adjust_multiple_ffi")(fields)

/proc/dogmos_mixture_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_command_ffi")(fields)

/proc/dogmos_mixture_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_lifecycle_batch_ffi")(entries)

/proc/dogmos_mixture_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_snapshot_ffi")(fields)

/proc/dogmos_mixture_state_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_state_batch_ffi")(entries)

/proc/dogmos_process_metrics()
	return call_ext(DOGMOS, "byond:dogmos_process_metrics_ffi")()

/proc/dogmos_protocol_version()
	return call_ext(DOGMOS, "byond:dogmos_protocol_version_ffi")()

/proc/dogmos_reaction_metadata_install(numeric_records, keys, requirement_records)
	return call_ext(DOGMOS, "byond:dogmos_reaction_metadata_install_ffi")(numeric_records, keys, requirement_records)

/proc/dogmos_service_health()
	return call_ext(DOGMOS, "byond:dogmos_service_health_ffi")()

/proc/dogmos_service_pid()
	return call_ext(DOGMOS, "byond:dogmos_service_pid_ffi")()

/proc/dogmos_service_shutdown()
	return call_ext(DOGMOS, "byond:dogmos_service_shutdown_ffi")()

/proc/dogmos_service_start(service_path)
	return call_ext(DOGMOS, "byond:dogmos_service_start_ffi")(service_path)

/proc/dogmos_service_telemetry()
	return call_ext(DOGMOS, "byond:dogmos_service_telemetry_ffi")()

/proc/dogmos_service_world_generation()
	return call_ext(DOGMOS, "byond:dogmos_service_world_generation_ffi")()

/proc/dogmos_simulation_stage(fields)
	return call_ext(DOGMOS, "byond:dogmos_simulation_stage_ffi")(fields)

/proc/dogmos_source_revision()
	return call_ext(DOGMOS, "byond:dogmos_source_revision_ffi")()

/proc/dogmos_turf_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_batch_ffi")(entries)

/proc/dogmos_turf_heat_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_snapshot_ffi")(fields)

/proc/dogmos_turf_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_lifecycle_batch_ffi")(entries)
