//THIS FILE IS AUTOMATICALLY GENERATED BY DOGMOS_BYOND, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

/* This comment bypasses grep checks */ /var/__dogmos_byond

/proc/__detect_dogmos_byond()
	if (world.system_type == UNIX)
		return __dogmos_byond = "libdogmos_byond"
	else
		return __dogmos_byond = "dogmos_byond"

#define DOGMOS_BYOND (__dogmos_byond || __detect_dogmos_byond())

/proc/dogmos_ipc_benchmark_stop()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_stop_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_scalar_get()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_scalar_get_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_allocate(bytes)
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_allocate_ffi")
	return call_ext(loaded)(bytes)

/proc/dogmos_ipc_benchmark_clock_microseconds()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_clock_microseconds_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_service_pid()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_service_pid_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_callback_drain(max_events)
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_callback_drain_ffi")
	return call_ext(loaded)(max_events)

/proc/dogmos_ipc_benchmark_callback_enqueue(count)
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_callback_enqueue_ffi")
	return call_ext(loaded)(count)

/proc/dogmos_ipc_benchmark_simulation_stage()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_simulation_stage_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_adjacency_batch()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_adjacency_batch_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_state_batch()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_state_batch_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_lifecycle_batch()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_lifecycle_batch_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_snapshot()
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_snapshot_ffi")
	return call_ext(loaded)()

/proc/dogmos_ipc_benchmark_start(service_path)
	var/static/loaded = load_ext(DOGMOS_BYOND, "byond:dogmos_ipc_benchmark_start_ffi")
	return call_ext(loaded)(service_path)

