[package]
name = "dogmos-byond"
version = "2.3.0"
edition = "2021"

[features]
diagnostic-bindings = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
auxmacros = { path = "../auxmacros" }
byondapi = { workspace = true }
dogmos-identity = { path = "../dogmos-identity" }
dogmos-protocol = { path = "../dogmos-protocol" }
eyre = { workspace = true }
interprocess = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
